# Jupyter Book Configuration
title: SQL Learning Notes
author: Ranjan Kumar Choubey
logo: ""

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: force
  timeout: 300
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: sql-notes.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ranjanchoubey/sql-notes
  path_to_book: .
  branch: master  # Changed from main to master

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  html_theme: sphinx_book_theme
  html_theme_options:
    repository_url: https://github.com/ranjanchoubey/sql-notes
    use_repository_button: true
    use_issues_button: true
    use_edit_page_button: true
    use_download_button: true
    use_fullscreen_button: true
    home_page_in_toc: false
    show_navbar_depth: 2
    logo:
      text: "SQL Learning Notes"
    # Color scheme
    primary_sidebar_end: []
    article_header_start: []
    content_footer_items: []

# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist
    - html_admonition
    - html_image
  
# File formats and handling
sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.viewcode
  config:
    html_theme_options:
      repository_url: https://github.com/ranjanchoubey/sql-notes
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
    # Allow HTML files to be included
    html_static_path: ['_static', 'assets']
    # Configure file handling
    source_suffix:
      '.md': 'myst-nb'
      '.ipynb': 'myst-nb'
      '.rst': 'restructuredtext'

# Sphinx configuration
sphinx:
  config:
    html_theme_options:
      repository_url: https://github.com/ranjanchoubey/sql-notes
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
