name: deploy-book

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build the book
      run: |
        jupyter-book build .

    - name: Copy build to docs folder and create proper index.html
      run: |
        rm -rf docs/
        mkdir -p docs/
        cp -r _build/html/* docs/
        
        # Ensure index.html is the main entry point (from sql-notes.ipynb)
        if [ -f "docs/sql-notes.html" ]; then
          cp docs/sql-notes.html docs/index.html
        fi
        
        touch docs/.nojekyll
        ls -la docs/

    - name: Verify index.html exists
      run: |
        if [ ! -f "docs/index.html" ]; then
          echo "ERROR: index.html not found in docs folder!"
          exit 1
        fi
        echo "✅ index.html found at docs/index.html"

    - name: Commit and push docs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git diff --staged --quiet || git commit -m "Deploy Jupyter Book to docs folder"
        git push
